### ISSUE TITLE
Set up scheduled requests for temperature checkins

### ISSUE THREAD

**Issue by reshadbinharun** [reshadbinharun/covid-temp-scheduler#5]
* should be incorporated as part of `ingest/csvFile` API
* should store data about new users in mongoDB
* should make a TWILIO API call for `doYouHaveThermometer` API (need to consult with @duci9y)

**Comment by awilli70** [comment]
New Users and hasThermo (doYouHaveThermometer) stored in database after first call - information gathering for first call can be adjusted in Studio First Call flow and adding additional fields to the firstCallAnswered route in mongo.js
